### ISSUE TITLE
Not able to build apk when running gradle from CLI

### ISSUE THREAD

**Issue by diegotmorais** [sephiroth74/NumberSlidingPicker#1]
23:27:14 + ./gradlew assembleDebug
23:27:17 
23:27:17 FAILURE: Build failed with an exception.
23:27:17 
23:27:17 * What went wrong:
23:27:17 Could not determine the dependencies of task ':app:preDebugBuild'.
23:27:17 > Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
23:27:17    > Could not find com.github.sephiroth74:android-target-tooltip:feature~update_text_and_position-SNAPSHOT.
23:27:17      Searched in the following locations:
23:27:17        - file:/home/centos/android_tools/extras/m2repository/com/github/sephiroth74/android-target-tooltip/feature~update_text_and_position-SNAPSHOT/maven-metadata.xml
23:27:17        - file:/home/centos/android_tools/extras/m2repository/com/github/sephiroth74/android-target-tooltip/feature~update_text_and_position-SNAPSHOT/android-target-tooltip-feature~update_text_and_position-SNAPSHOT.pom
23:27:17        - file:/home/centos/android_tools/extras/m2repository/com/github/sephiroth74/android-target-tooltip/feature~update_text_and_position-SNAPSHOT/android-target-tooltip-feature~update_text_and_position-SNAPSHOT.jar
23:27:17        - file:/home/centos/android_tools/extras/google/m2repository/com/github/sephiroth74/android-target-tooltip/feature~update_text_and_position-SNAPSHOT/maven-metadata.xml
23:27:17        - file:/home/centos/android_tools/extras/google/m2repository/com/github/sephiroth74/android-target-tooltip/feature~update_text_and_position-SNAPSHOT/android-target-tooltip-feature~update_text_and_position-SNAPSHOT.pom
23:27:17        - file:/home/centos/android_tools/extras/google/m2repository/com/github/sephiroth74/android-target-tooltip/feature~update_text_and_position-SNAPSHOT/android-target-tooltip-feature~update_text_and_position-SNAPSHOT.jar
23:27:17        - file:/home/centos/android_tools/extras/android/m2repository/com/github/sephiroth74/android-target-tooltip/feature~update_text_and_position-SNAPSHOT/maven-metadata.xml
23:27:17        - file:/home/centos/android_tools/extras/android/m2repository/com/github/sephiroth74/android-target-tooltip/feature~update_text_and_position-SNAPSHOT/android-target-tooltip-feature~update_text_and_position-SNAPSHOT.pom
23:27:17        - file:/home/centos/android_tools/extras/android/m2repository/com/github/sephiroth74/android-target-tooltip/feature~update_text_and_position-SNAPSHOT/android-target-tooltip-feature~update_text_and_position-SNAPSHOT.jar
23:27:17        - https://dl.google.com/dl/android/maven2/com/github/sephiroth74/android-target-tooltip/feature~update_text_and_position-SNAPSHOT/maven-metadata.xml
23:27:17        - https://dl.google.com/dl/android/maven2/com/github/sephiroth74/android-target-tooltip/feature~update_text_and_position-SNAPSHOT/android-target-tooltip-feature~update_text_and_position-SNAPSHOT.pom
23:27:17        - https://dl.google.com/dl/android/maven2/com/github/sephiroth74/android-target-tooltip/feature~update_text_and_position-SNAPSHOT/android-target-tooltip-feature~update_text_and_position-SNAPSHOT.jar
23:27:17        - https://jcenter.bintray.com/com/github/sephiroth74/android-target-tooltip/feature~update_text_and_position-SNAPSHOT/maven-metadata.xml
23:27:17        - https://jcenter.bintray.com/com/github/sephiroth74/android-target-tooltip/feature~update_text_and_position-SNAPSHOT/android-target-tooltip-feature~update_text_and_position-SNAPSHOT.pom
23:27:17        - https://jcenter.bintray.com/com/github/sephiroth74/android-target-tooltip/feature~update_text_and_position-SNAPSHOT/android-target-tooltip-feature~update_text_and_position-SNAPSHOT.jar
23:27:17        - https://jitpack.io/com/github/sephiroth74/android-target-tooltip/feature~update_text_and_position-SNAPSHOT/maven-metadata.xml
23:27:17        - https://jitpack.io/com/github/sephiroth74/android-target-tooltip/feature~update_text_and_position-SNAPSHOT/android-target-tooltip-feature~update_text_and_position-SNAPSHOT.pom
23:27:17        - https://jitpack.io/com/github/sephiroth74/android-target-tooltip/feature~update_text_and_position-SNAPSHOT/android-target-tooltip-feature~update_text_and_position-SNAPSHOT.jar
23:27:17      Required by:
23:27:17          project :app > com.github.sephiroth74:NumberSlidingPicker:1.0.0

**Comment by Shailevy** [comment]
Same here

**Comment by diegotmorais** [comment]
@Shailevy please let me know if you find any workaround for that. thanks.
