### ISSUE TITLE
does it work with databinding

### ISSUE THREAD

**Issue by khraibani-h** [sephiroth74/NumberSlidingPicker#9]
Dear Sir 
have You tried it with databinding best regards

**Comment by khraibani-h** [comment]
package com.tayibat.utilities;

import androidx.databinding.BindingAdapter;
import androidx.databinding.InverseBindingListener;
import androidx.databinding.InverseBindingMethod;
import androidx.databinding.InverseBindingMethods;

import it.sephiroth.android.library.numberpicker.NumberPicker;



@InverseBindingMethods({
        @InverseBindingMethod(type = NumberPicker.class, attribute = "android:progress"),
})

public class NumberPickerBindingAdapter {

    @BindingAdapter("android:progress")
    public static void setProgress(NumberPicker view, int progress) {
        if (progress != view.getProgress()) {
            view.setProgress(progress);
        }
    }


    @BindingAdapter(value = {"android:onStartTrackingTouch", "android:onStopTrackingTouch",
            "android:onProgressChanged", "android:progressAttrChanged"}, requireAll = false)


    public static void setOnSeekBarChangeListener(NumberPicker view, final OnStartTrackingTouch start,
                                                  final OnStopTrackingTouch stop, final OnProgressChanged progressChanged,
                                                  final InverseBindingListener attrChanged) {
        if (start == null && stop == null && progressChanged == null && attrChanged == null) {
            view.setNumberPickerChangeListener(null);
        } else {
            view.setNumberPickerChangeListener(new NumberPicker.OnNumberPickerChangeListener() {
                @Override
                public void onProgressChanged(NumberPicker seekBar, int progress, boolean fromUser) {
                    if (progressChanged != null) {
                        progressChanged.onProgressChanged(seekBar, progress, fromUser);
                    }
                    if (attrChanged != null) {
                        attrChanged.onChange();
                    }
                }

                @Override
                public void onStartTrackingTouch(NumberPicker seekBar) {
                    if (start != null) {
                        start.onStartTrackingTouch(seekBar);
                    }
                }

                @Override
                public void onStopTrackingTouch(NumberPicker seekBar) {
                    if (stop != null) {
                        stop.onStopTrackingTouch(seekBar);
                    }
                }
            });
        }
    }

    public interface OnStartTrackingTouch {
        void onStartTrackingTouch(NumberPicker seekBar);
    }

    public interface OnStopTrackingTouch {
        void onStopTrackingTouch(NumberPicker seekBar);
    }

    public interface OnProgressChanged {
        void onProgressChanged(NumberPicker seekBar, int progress, boolean fromUser);
    }
}

**Comment by khraibani-h** [comment]
i tried ur library several times ... ended up not using it untill i was testing today .. and this how databinding worked

**Comment by khraibani-h** [comment]
//DATABINDING FOR this library:
//managed to make it work.
package net.tayibat.app.utilities;

import androidx.databinding.BindingAdapter;
import androidx.databinding.InverseBindingListener;
import androidx.databinding.InverseBindingMethod;
import androidx.databinding.InverseBindingMethods;

import it.sephiroth.android.library.numberpicker.NumberPicker;



@InverseBindingMethods({
        @InverseBindingMethod(type = NumberPicker.class, attribute = "android:progress"),
})

public class NumberPickerBindingAdapter {


    @BindingAdapter(value = {"android:onStartTrackingTouch", "android:onStopTrackingTouch",
            "android:onProgressChanged", "android:progressAttrChanged"}, requireAll = false)


    public static void setOnSeekBarChangeListener(NumberPicker view, final OnStartTrackingTouch start,
                                                  final OnStopTrackingTouch stop, final OnProgressChanged progressChanged,
                                                  final InverseBindingListener attrChanged) {
        //// Log.d(TAG, "setOnSeekBarChangeListener: called");
        if (start == null && stop == null && progressChanged == null && attrChanged == null) {
            view.setNumberPickerChangeListener(null);
        } else {
            view.setNumberPickerChangeListener(new NumberPicker.OnNumberPickerChangeListener() {
                @Override
                public void onProgressChanged(NumberPicker seekBar, int progress, boolean fromUser) {
                    if (progressChanged != null) {
                        progressChanged.onProgressChanged(seekBar, progress, fromUser);
                    }
                    if (attrChanged != null) {
                        attrChanged.onChange();
                    }
                }

                @Override
                public void onStartTrackingTouch(NumberPicker seekBar) {
                    if (start != null) {
                        start.onStartTrackingTouch(seekBar);
                    }
                }

                @Override
                public void onStopTrackingTouch(NumberPicker seekBar) {
                    if (stop != null) {
                        stop.onStopTrackingTouch(seekBar);
                    }
                }
            });
        }
    }

    public interface OnStartTrackingTouch {
        void onStartTrackingTouch(NumberPicker seekBar);
    }

    public interface OnStopTrackingTouch {
        void onStopTrackingTouch(NumberPicker seekBar);
    }

    public interface OnProgressChanged {
        void onProgressChanged(NumberPicker seekBar, int progress, boolean fromUser);

    }


}

**Comment by sephiroth74** [comment]
Hi,
Do you want to create a PR for this?

**Comment by sephiroth74** [comment]
ok, added to master
